import React, { useContext, useState, useEffect } from "react";
import NavMenu from "./NavMenu";
import { NavLink } from "react-router-dom";
import styled from "styled-components";
import UserContext from "../context/user/userContext";
import firebase from "../firebase/firebase.utils";
import "firebase/auth";
import tmplo from "./tmplo.png";

const HeaderDiv = styled.div`
  display: flex;
  flex-direction: row;
  justify-content: space-between;
  padding: 5px 12px;
  width: 92%;
  height: 100px;
  margin: 0px auto 20px auto;
  border-radius: 2px;
  border: 1px solid rgba(0, 0, 0, 0.1);
  border-top: none;
  -webkit-animation: slide-in-top 0.4s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
  animation: slide-in-top 0.4s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;

  h1 {
    font-size: 1.25em;
    font-family: "Merriweather", serif;
    border-bottom: 2px solid #6cc444;
    display: flex;
    justify-content: center;
    align-items: center;
  }

  img {
    height: 38px;
    margin: 4px;
  }

  a {
    font-family: "Merriweather Sans";
    text-decoration: none;
    color: black;
  }

  a:hover {
    text-decoration: wavy;
    color: black;
  }

  @media (max-width: 800px) {
    text-align: center;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    width: 100%;
    height: 150px;

    h1 {
      width: 100%;
      justify-content: flex-start;
    }

    img {
      padding-right: 8px;
    }
  }

  /* ----------------------------------------------
 * Generated by Animista on 2019-8-16 22:19:15
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

  /**
 * ----------------------------------------
 * animation slide-in-top
 * ----------------------------------------
 */
  @-webkit-keyframes slide-in-top {
    0% {
      -webkit-transform: translateY(-1000px);
      transform: translateY(-1000px);
      opacity: 0;
    }
    100% {
      -webkit-transform: translateY(0);
      transform: translateY(0);
      opacity: 1;
    }
  }
  @keyframes slide-in-top {
    0% {
      -webkit-transform: translateY(-1000px);
      transform: translateY(-1000px);
      opacity: 0;
    }
    100% {
      -webkit-transform: translateY(0);
      transform: translateY(0);
      opacity: 1;
    }
  }
`;

const SideBar = styled.div`
  display: flex;
  justify-content: flex-end;
  align-items: center;

  @media (max-width: 500px) {
    flex-direction: column;
  }
`;

const Header = props => {
  const userContext = useContext(UserContext);
  const auth = firebase.auth();
  const db = firebase.firestore();
  const [loggedIn, setLoggedIn] = useState(false);
  //
  useEffect(() => {
    if (loggedIn === false) {
      firebase.auth().onAuthStateChanged(function(user) {
        if (user) {
          const userDB = db.collection("users").doc(`${auth.currentUser.uid}`);
          userDB
            .get()
            .then(function(user) {
              userContext.addUser(user.data());
            })
            .catch(function(error) {
              console.log(error);
            });
          loggedInToTrue();
        } else {
          props.history.push("/landing");
        }
      });
    }
  }, {});
  const loggedInToTrue = () => {
    setLoggedIn(true);
  };
  //
  const signOut = () => {
    auth
      .signOut()
      .then(() => {
        setLoggedIn(false);
        userContext.setLogin(false);
      })
      .catch(function(error) {
        console.log(error);
      });
  };
  return (
    <div>
      {loggedIn ? (
        <HeaderDiv>
          <h1>
            <img src={tmplo} />
            <NavLink to="/">Neighborhood Library</NavLink>
          </h1>
          <SideBar>
            <NavMenu signOut={signOut} />
          </SideBar>
        </HeaderDiv>
      ) : (
        ""
      )}
    </div>
  );
};

export default Header;
