import React, { useContext, useState, useEffect } from "react";
import NavMenu from "./NavMenu";
import { NavLink } from "react-router-dom";
import styled from "styled-components";
import UserContext from "../context/user/userContext";
import firebase from "../firebase/firebase.utils";
import "firebase/auth";
import tmplo from "./tmplo.png";

const HeaderDiv = styled.div`
  display: flex;
  flex-direction: row;
  justify-content: space-between;
  padding: 10px 17px;
  width: 88%;
  margin: 0px auto 20px auto;
  border-radius: 2px;
  border: 1px solid rgba(0,0,0,.1);
  border-top: none;
  -webkit-box-shadow:3px 4.5px 4px 0px #bfbfbf ;
  -moz-box-shadow:3px 4.5px 4px 0px #bfbfbf ;
  box-shadow:3px 4.5px 4px 0px #bfbfbf ;
  -webkit-animation: slide-in-top 0.4s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
          animation: slide-in-top 0.4s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;


  h1 {
    font-size: 1.5em;
    font-family: "Merriweather", serif;
    border-bottom: 2px solid #6CC444;
    display: flex;
    justify-content: center;
    align-items: center;
  }

  img {
    height: 75px;
    margin: 10px;
  }

  a {
    font-family: 'Merriweather Sans';
    text-decoration: none;
    color: black;
  }

  a:hover {
    text-decoration: wavy;
    color: black;
  }

  @media (max-width: 800px) {
    text-align: center;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    width: 100%;

    h1 {
      width: 100%;
    }
  }

  /* ----------------------------------------------
 * Generated by Animista on 2019-8-16 22:19:15
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-in-top
 * ----------------------------------------
 */
@-webkit-keyframes slide-in-top {
  0% {
    -webkit-transform: translateY(-1000px);
            transform: translateY(-1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0);
            transform: translateY(0);
    opacity: 1;
  }
}
@keyframes slide-in-top {
  0% {
    -webkit-transform: translateY(-1000px);
            transform: translateY(-1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0);
            transform: translateY(0);
    opacity: 1;
  }
}

`;

const SideBar = styled.div`
  display: flex;
  justify-content: flex-end;
  align-items: center;

  @media (max-width: 500px) {
    flex-direction: column;
  }
`;

const Header = props => {
  const userContext = useContext(UserContext);
  const auth = firebase.auth();
  const db = firebase.firestore();
  const [loggedIn, setLoggedIn] = useState(false);
  //
  useEffect(() => {
    if (loggedIn === false) {
      firebase.auth().onAuthStateChanged(function(user) {
        if (user) {
          const userDB = db.collection("users").doc(`${auth.currentUser.uid}`);
          userDB
            .get()
            .then(function(user) {
              userContext.addUser(user.data());
              // props.history.push('/shelf');
            })
            .catch(function(error) {
              console.log(error);
            });
          loggedInToTrue();
        } else {
          props.history.push("/landing");
        }
      });
    }
  }, {});
  const loggedInToTrue = () => {
    setLoggedIn(true);
  };
  //
  const signOut = () => {
    auth
      .signOut()
      .then(() => {
        setLoggedIn(false);
        userContext.setLogin(false);
      })
      .catch(function(error) {});
  };
  return (
    <div>
      {loggedIn ? (
        <HeaderDiv>
          <h1>
            <img src={tmplo} />
            <NavLink to="/shelf">Neighborhood Library</NavLink>
          </h1>
          <SideBar>
            <NavMenu signOut={signOut} />
          </SideBar>
        </HeaderDiv>
      ) : (
        ""
      )}
    </div>
  );
};

export default Header;
