import React, { useState, useEffect, useContext } from "react";
import UserContext from "../../context/user/userContext";
import { Jumbotron } from "reactstrap";
import styled from 'styled-components';

//SHELF PLUGS
import Analytics from "./Plugs/Analytics";
import UserInfo from "./Plugs/UserInfo";

const MainShelfDiv = styled.div`
  display: grid;
  grid-template-columns: 1fr 1fr 1fr 1fr;
  grid-template-areas:
    'jm jm jm uin'
    'jm jm jm an' ;
  grid-gap: 10px;
  align-items: center;
  justify-content: center;

  #analytics {
    grid-area: an;
  }

  #userinfo {
    grid-area: uin;
  }

  @media(max-width: 800px){
    display: flex;
    flex-direction: column;
  }
`

const IntroNew = styled.div`
  height: 100%;
  width: 100%;
  border-radius: 2px;
  background-color: rgba(0,0,0,0.03);
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  -webkit-animation: fade-in 0.8s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
  animation: fade-in 0.8s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
  grid-area: jm;

  h2 {
    font-size: 1.3em;
    font-family: 'Merriweather Sans';
  }

  h3 {
    font-size: 0.8em;
    font-color: rgba(0,0,0,.9);
  }

  @media(max-width: 600px) {

  }

    /* ----------------------------------------------
  * Generated by Animista on 2019-8-16 22:16:30
  * w: http://animista.net, t: @cssanimista
  * ---------------------------------------------- */

  /**
   * ----------------------------------------
   * animation fade-in
   * ----------------------------------------
   */
  @-webkit-keyframes fade-in {
    0% {
      opacity: 0;
    }
    100% {
      opacity: 1;
    }
  }
  @keyframes fade-in {
    0% {
      opacity: 0;
    }
    100% {
      opacity: 1;
    }
  }

`

export default function MainShelf() {
  const userContext = useContext(UserContext);
  const [user, setUser] = useState({});

  const getUser = () => {
    setUser(userContext.getUser());
  };
  useEffect(() => {
    getUser();
  }, {});

  return (
    <MainShelfDiv>
        <UserInfo id="userinfo" />
        <Analytics id="analytics"/>
        <IntroNew id="jumbo">
          <h2>
            Hello {user.displayName}! Welcome to your shelf.
          </h2>
          <h3>Use the tabs above to navigate</h3>
        </IntroNew>
    </MainShelfDiv>
  );
}
