import React, { useState, useEffect, useContext } from "react";
import UserContext from "../../context/user/userContext";
import styled from "styled-components";

//SHELF PLUGS
import Analytics from "./Plugs/Analytics";
import UserInfo from "./Plugs/UserInfo";
import BooksInfo from "./Plugs/BooksInfo";

const MainShelfDiv = styled.div`
  display: grid;
  color: rgb(50,50,50);
  grid-template-columns: 1fr 1fr 1fr 1fr;
  grid-template-areas:
    "bntop bntop bntop bntop"
    "bkin bkin bkin uin"
    "bkin bkin bkin an";
  align-items: stretch;
  justify-items: center;

  #analytics {
    grid-area: an;
  }

  #banTop {
    grid-area: bntop;
    font-family: 'Merriweather', sans-serif;
    background-color: rgb(80,80,80);
    color: rgb(232,232,232);
    padding: 10px;
    border-radius: 3px;
    font-size: 0.9em;
    padding-left: 14px;
    width: 100%;
    border: 1px solid rgba(0,0,0,.2);
  }

  #userinfo {
    grid-area: uin;
  }

  #booksinfo {
    grid-area: bkin;
  }

  @media (max-width: 800px) {
    display: flex;
    flex-direction: column;
  }
`;

const IntroNew = styled.div`
  height: 100%;
  width: 100%;
  border-radius: 2px;
  background-color: rgba(0, 0, 0, 0.03);
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  -webkit-animation: fade-in 0.8s cubic-bezier(0.39, 0.575, 0.565, 1) both;
  animation: fade-in 0.8s cubic-bezier(0.39, 0.575, 0.565, 1) both;
  grid-area: jm;

  h2 {
    font-size: 1.3em;
    font-family: "Merriweather Sans";
  }

  h3 {
    font-size: 0.8em;
    font-color: rgba(0, 0, 0, 0.9);
  }

  @media (max-width: 600px) {
  }

  /* ----------------------------------------------
  * Generated by Animista on 2019-8-16 22:16:30
  * w: http://animista.net, t: @cssanimista
  * ---------------------------------------------- */

  /**
   * ----------------------------------------
   * animation fade-in
   * ----------------------------------------
   */
  @-webkit-keyframes fade-in {
    0% {
      opacity: 0;
    }
    100% {
      opacity: 1;
    }
  }
  @keyframes fade-in {
    0% {
      opacity: 0;
    }
    100% {
      opacity: 1;
    }
  }
`;

export default function MainShelf() {
  const userContext = useContext(UserContext);
  const [user, setUser] = useState({});

  const getUser = () => {
    setUser(userContext.getUser());
  };
  useEffect(() => {
    getUser();
  }, {});

  return (
    <MainShelfDiv>
      <div id="banTop">Welcome to your shelf {user.displayName}</div>
      <BooksInfo />
      <UserInfo id="userinfo" />
      <Analytics id="analytics" />
    </MainShelfDiv>
  );
}
